### ISSUE TITLE
500 internal server error on config flow

### ISSUE THREAD

**Issue by r3wt** [iKaew/hass-linkstation-addon#1]
Home Assistant Core 2022.5.3
Home Assistant Supervisor 2022.05.1

```
Logger: aiohttp.server
Source: helpers/data_entry_flow.py:43
First occurred: 8:18:44 AM (1 occurrences)
Last logged: 8:18:44 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 196, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 99, in get
    result = self._prepare_result_json(result)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 209, in _prepare_result_json
    return _prepare_config_flow_result_json(result, super()._prepare_result_json)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 147, in _prepare_config_flow_result_json
    return prepare_result_json(result)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 43, in _prepare_result_json
    data["data_schema"] = voluptuous_serialize.convert(
  File "/usr/local/lib/python3.9/site-packages/voluptuous_serialize/__init__.py", line 40, in convert
    pval = convert(value, custom_serializer=custom_serializer)
  File "/usr/local/lib/python3.9/site-packages/voluptuous_serialize/__init__.py", line 107, in convert
    if schema in TYPES_MAP:
TypeError: unhashable type: 'list'
```
Explanation: I followed your instructions and then restarted home assistant. immediately it got notification of LinkStation device available. clicking the "configure" button on the device, results in 500 response from server. I went and checked the logs and see this message. I couldn't understand what the issue is.

**Comment by iKaew** [comment]
Hi r3wt, let me test against the same HA version and get back to you on this.

**Comment by iKaew** [comment]
Hi @r3wt,

I just run test with latest dev version (`2022.6.0.dev0`), It seems working fine. 

Could you share your `configuration.xml` that set the Link station detail? 

Something like 

```
linkstation:
  name: NAS
  host: 192.168.1.X
  username: (Redacted)
  password: (Redacted)
  scan_interval: 60 # 15 mins
```

**Comment by r3wt** [comment]
```
linkstation:
  name: NAS
  host: 192.168.50.18 # LinkStation IP Address
  username: !secret linkstation_username
  password: !secret linkstation_password
  scan_interval: 10 # minutes
```

**Comment by carloda** [comment]
I also have the same problem ...

**Comment by iKaew** [comment]
ok. I'll try clean and do a fresh install on my environment.

**Comment by carloda** [comment]
@iKaew  this is my configuration:

Home Assistant 2022.10.3
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest

**Comment by acrylicus** [comment]
I am getting this too in late 2023

**Comment by Martyello** [comment]
I also have the same problem:  
![image](https://github.com/iKaew/hass-linkstation-addon/assets/153554580/a80e8266-9910-4568-8a63-a162445b1380)

linkstation:
    name: LinkStation
    host: 192.168.2.2 # LinkStation IP Address
    username: user
    password: password
    scan_interval: 30 # minutes

new instalation of home assistant

**Comment by iKaew** [comment]
This should be fixed in the latest version
