### ISSUE TITLE
not working since 2025.1

### ISSUE THREAD

**Issue by jejsun** [iKaew/hass-linkstation-addon#6]
Hi, 

This seems to need some tweaking since last releases, would be wonderful if you could fix it! 
Havent found another integration vs Buffalo/Linkstation

Thanks!

Logmsg;
2024-02-20 16:29:34.204 WARNING (MainThread) [homeassistant.const] DATA_GIGABYTES was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfInformation.GIGABYTES instead, please report it to the author of the 'linkstation' custom integration
2024-02-20 16:29:34.206 WARNING (MainThread) [homeassistant.components.sensor] STATE_CLASS_MEASUREMENT was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'linkstation' custom integration
2024-02-20 16:29:34.208 WARNING (MainThread) [homeassistant.components.sensor] STATE_CLASS_MEASUREMENT was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'linkstation' custom integration
2024-02-20 16:29:34.210 WARNING (MainThread) [homeassistant.const] DATA_GIGABYTES was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfInformation.GIGABYTES instead, please report it to the author of the 'linkstation' custom integration

**Comment by iKaew** [comment]
Since I have no linkstation with me anymore. However, I will try to fix the compatibility with new HA. I'll let you know when this get fixed.

**Comment by iKaew** [comment]
@jejsun Can you share more logs ?

The logs you post above are warnings that will stop working in 2025.1, which is next year. current version is 2024.2.

**Comment by jejsun** [comment]
oh, I'm living in the future, need to reinstall to check again for more logs, will do later today

**Comment by jejsun** [comment]
2024-02-27 16:25:32.701 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration linkstation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-27 16:26:12.282 WARNING (MainThread) [homeassistant.const] DATA_GIGABYTES was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfInformation.GIGABYTES instead, please report it to the author of the 'linkstation' custom integration
2024-02-27 16:26:12.284 WARNING (MainThread) [homeassistant.components.sensor] STATE_CLASS_MEASUREMENT was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'linkstation' custom integration
2024-02-27 16:26:12.286 WARNING (MainThread) [homeassistant.components.sensor] STATE_CLASS_MEASUREMENT was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'linkstation' custom integration
2024-02-27 16:26:12.288 WARNING (MainThread) [homeassistant.const] DATA_GIGABYTES was used from linkstation, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfInformation.GIGABYTES instead, please report it to the author of the 'linkstation' custom integration
2024-02-27 16:26:12.305 ERROR (MainThread) [homeassistant] Error doing job: Unclosed client session
2024-02-27 16:26:12.305 ERROR (MainThread) [homeassistant] Error doing job: Unclosed connector
2024-02-27 16:27:50.365 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 178, in get
    return await super().get(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 100, in get
    result = self._prepare_result_json(result)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 191, in _prepare_result_json
    return _prepare_config_flow_result_json(result, super()._prepare_result_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 128, in _prepare_config_flow_result_json
    return prepare_result_json(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 44, in _prepare_result_json
    data["data_schema"] = voluptuous_serialize.convert(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous_serialize/__init__.py", line 40, in convert
    pval = convert(value, custom_serializer=custom_serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/voluptuous_serialize/__init__.py", line 114, in convert
    if schema in TYPES_MAP:
       ^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'

**Comment by jejsun** [comment]
logs from a fresh try, the last logs around the deprecation 2025 was just a future problem, more issues below

**Comment by iKaew** [comment]
Ok, thanks. Look like it's a compatibility issue with Python 3.12. I'll take a look as soon as I can.

**Comment by iKaew** [comment]
Fixed in latest version
